[package]
name = "fundloom_starknet"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
starknet = ">=2.3.0"

[[target.starknet-contract]]
# Enable the Sierra code generation in the default profile
disallowed-libfuncs = ["starknet"]
allowed-libfuncs = ["starknet::starknet_libfunc"]
